name: webpage deploy

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Upload via SCP
        uses: betanzos/scp-upload@v1
        with:
          source: ${{ github.workspace }}
          host: ${{secrets.HOST}}
          port: ${{secrets.PORT}}
          username: ${{secrets.USER}}
          key: ${{secrets.PRIVATE_KEY}}
          remote_dir: ~
          recursive: true

      - name: Execute Remote Deploy Script via SSH
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{secrets.HOST}}
          port: ${{secrets.PORT}}
          user: ${{secrets.USER}}
          private_key: ${{secrets.PRIVATE_KEY}}
          host_fingerprint: ${{secrets.HOST_FINGERPRINT}}
          command: ~/workspace/scripts/remote_update.sh
